Change Story in Editor
alanorozco/amp-story-ads-preview pull request #58
Opened 2019-07-19 20:01 UTC by bhassan6621

added a "story" button in editor that allows you to change the story rendered html, saves that edit in the state and updates the storyAd, so when you go back to the Ad's code in the html the changes you made to the story will appear there as well.

2019-07-22 17:26 UTC, alanorozco submitted a review, later dismissed

2019-07-22 17:26 UTC, alanorozco commented on src/modify-storyAd.js
> +// function cascadeInputClick({currentTarget}) {
Remove commented-out code? :)

2019-07-22 17:26 UTC, alanorozco commented on src/modify-storyAd.js
> +const dispatchModifyStoryAd = redispatchAs(g('modify-storyAd'));
Let's rename this to "toggle inner outer" with all relevant units renamed to this as well.

2019-07-22 17:26 UTC, alanorozco commented on src/modify-storyAd.js
> +const {g} = getNamespace('modify-storyAd');
`toggle-inner-outer`

2019-07-22 17:26 UTC, alanorozco commented on src/modify-storyAd.js
> +export const ChangeDefaultStory = ({editingInner}) => html`
`ToggleInnerOuterContentButton`

2019-07-22 17:26 UTC, alanorozco commented on src/editor.js
> +  editingInner = true,
Let's rename to `isEditingInner` for consistency.

2019-07-30 17:37 UTC, calebcordry commented
@bhassan6621 is this ready for review?

2019-07-30 20:35 UTC, bhassan6621 commented
> @bhassan6621 is this ready for review?

yes it's ready

2019-08-01 19:51 UTC, alanorozco commented on src/story-patch.js
> +export const cssPatch = minifyInlineJs(`
Ah, don't `minifyInlineJs` this since it's `css`.

2019-08-02 17:02 UTC, calebcordry requested changes
Looks good in general, just a couple of questions.

2019-08-02 17:02 UTC, calebcordry commented on src/amp-story-ad-preview.js
> +  async updateInnerInStory(dirty) {
Should this method just be part of `updateOuter`?

2019-08-02 17:33 UTC, bhassan6621 commented on src/amp-story-ad-preview.js
> +const addCssToHead = (docStr, headContent) =>
yeah its pretty much the same, netlify didnt allow '<script>' tags inside minifyInlineJS() so i had to put the script tags in the addScriptToHead function, and I couldnt put the css inside the script tags so i made another const for adding the css

2019-08-02 19:24 UTC, calebcordry commented on src/amp-story-ad-preview.js
> +const addCssToHead = (docStr, headContent) =>
You are right here :) I missed the style vs script.

2019-08-02 19:24 UTC, calebcordry commented on src/amp-story-ad-preview.js
> +const storyCssPatch = docStr => addCssToHead(docStr, cssPatch);
lets just inline `addCssToHead` here

2019-08-05 19:09 UTC, calebcordry commented
@bhassan6621 Are you still working on this PR?

2019-08-05 19:09 UTC, calebcordry commented on src/amp-story-ad-preview.js
> +    this.adIframe_ = await awaitSelect(this.storyIframe_, 'iframe');
Sorry maybe I missed something, why is this resolved?

2019-08-26 21:13 UTC, calebcordry approved these changes

2019-08-26 21:14 UTC, merged

2019-08-26 21:15 UTC, calebcordry commented
@alanorozco merging this for now so that I can start on clean up work.